# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodSusceptibility
                                 A QGIS plugin
 Calculate flood susceptibility using DEM derivates and land use
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-14
        copyright            : (C) 2026 by Maíra T. de Camargo
        email                : maira.camargo@ufpr.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FloodSusceptibility class from file FloodSusceptibility.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flood_susceptibility import FloodSusceptibility
    return FloodSusceptibility(iface)
