# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodSusceptibility
                                 A QGIS plugin
 Calculate flood susceptibility using DEM derivates and land use
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Maíra T. de Camargo
        email                : maira.camargo@ufpr.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import math
import tempfile
import processing
from osgeo import gdal
from qgis.core import QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsRasterLayer, QgsProject, QgsRasterShader, QgsColorRampShader, QgsSingleBandPseudoColorRenderer
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction, QMessageBox

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .flood_susceptibility_dialog import FloodSusceptibilityDialog
import os.path


class FloodSusceptibility:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FloodSusceptibility_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Flood Susceptibility')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FloodSusceptibility', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/flood_susceptibility/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Flood Susceptibility'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Flood Susceptibility'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def get_copernicus_tiles(self, xmin, ymin, xmax, ymax):
        urls = []
        for lat in range(math.floor(ymin), math.ceil(ymax)):
            for lon in range(math.floor(xmin), math.ceil(xmax)):
                ns = "S" if lat < 0 else "N"
                ew = "W" if lon < 0 else "E"
                tile = (
                    f"Copernicus_DSM_COG_10_"
                    f"{ns}{abs(lat):02d}_00_"
                    f"{ew}{abs(lon):03d}_00_DEM"
                )
                url = (
                    f"/vsicurl/"
                    f"https://copernicus-dem-30m.s3.amazonaws.com/"
                    f"{tile}/{tile}.tif"
                )
                urls.append(url)
        return urls

    def get_hand_tiles(self, xmin, ymin, xmax, ymax):
        urls = []
        for lat in range(math.floor(ymin), math.ceil(ymax)):
            for lon in range(math.floor(xmin), math.ceil(xmax)):
                ns = "S" if lat < 0 else "N"
                ew = "W" if lon < 0 else "E"
                tile = (
                    f"Copernicus_DSM_COG_10_"
                    f"{ns}{abs(lat):02d}_00_"
                    f"{ew}{abs(lon):03d}_00_HAND"
                )
                url = (
                    f"/vsicurl/"
                    f"https://glo-30-hand.s3.us-west-2.amazonaws.com/"
                    f"v1/2021/{tile}.tif"
                )
                urls.append(url)
        return urls

    def get_utm_crs(self, xmin, xmax, ymin, ymax):
        centro_lon = (xmin + xmax) / 2
        centro_lat = (ymin + ymax) / 2

        zona = int((centro_lon + 180) / 6) + 1
        hemisferio = 'S' if centro_lat < 0 else 'N'

        if hemisferio == 'S':
            epsg = 32700 + zona
        else:
            epsg = 32600 + zona

        return f"EPSG:{epsg}"

    def adicionar_layer(self, path, nome):
        layer = QgsRasterLayer(path, nome)
        QgsProject.instance().addMapLayer(layer)

    def run(self):
        """Run method that performs all the real work"""
        if self.first_start == True:
            self.first_start = False
            self.dlg = FloodSusceptibilityDialog()
            # desconecta o "accept" automático do botão OK e conecta em
            # processar(), pra janela não fechar antes do processamento terminar
            try:
                self.dlg.button_box.accepted.disconnect()
            except TypeError:
                pass
            self.dlg.button_box.accepted.connect(self.processar)

        # reseta status 
        self.dlg.progressBar.setValue(0)
        self.dlg.label_status.setText("Status do processamento")

        self.dlg.mQgsFileWidget_output.lineEdit().setPlaceholderText("[Criar camada temporária]")

        self.dlg.show()
        self.dlg.exec_()

    def processar(self):
        """Executa todo o processamento de suscetibilidade à inundação."""

        # remove camadas de execuções anteriores, pra liberar os arquivos
        # antes de tentar sobrescrevê-los
        nomes_camadas_plugin = [
            "1. DEM",
            "2. Cobertura e Uso do Solo",
            "3. HAND",
            "4. Declividade",
            "5. Declividade Reclassificada",
            "6. HAND Reclassificado",
            "7. Cobertura e Uso do Solo Reclassificado",
            "Suscetibilidade à Inundação"
        ]
        for nome in nomes_camadas_plugin:
            for camada in QgsProject.instance().mapLayersByName(nome):
                QgsProject.instance().removeMapLayer(camada.id())

        tmp_path = tempfile.gettempdir()

        aoi_layer = self.dlg.mMapLayerComboBox_aoi.currentLayer()
        output_path = self.dlg.mQgsFileWidget_output.filePath()
        if not output_path:
            output_path = os.path.join(tmp_path, "suscetibilidade.tif")

        add_intermediate_layers = self.dlg.checkBox_intermediarias.isChecked()

        p_decliv = self.dlg.mQgsDoubleSpinBox_decliv.value()
        p_solo = self.dlg.mQgsDoubleSpinBox_solo.value()
        p_hand = self.dlg.mQgsDoubleSpinBox_hand.value()

        # valida se os pesos somam 1.0
        soma_pesos = p_decliv + p_solo + p_hand
        if abs(soma_pesos - 1.0) > 0.01:
            QMessageBox.warning(
                None,
                "Pesos inválidos",
                f"A soma dos pesos deve ser 1.0 (atual: {soma_pesos:.2f}). "
                "Ajuste os valores de Declividade, HAND e Uso do Solo."
            )
            return

        # extensão da AOI reprojetada para EPSG:4326
        extent = aoi_layer.extent()
        crs_4326 = QgsCoordinateReferenceSystem("EPSG:4326")
        if aoi_layer.crs() != crs_4326:
            transform = QgsCoordinateTransform(
                aoi_layer.crs(), crs_4326, QgsProject.instance()
            )
            extent = transform.transformBoundingBox(extent)

        xmin = extent.xMinimum()
        ymin = extent.yMinimum()
        xmax = extent.xMaximum()
        ymax = extent.yMaximum()

        aoi_path = aoi_layer.source()

        # DEM
        tiles = self.get_copernicus_tiles(xmin, ymin, xmax, ymax)
        vrt_path = os.path.join(tmp_path, "dem_mosaic.vrt")
        gdal.BuildVRT(vrt_path, tiles)

        utm_crs = self.get_utm_crs(xmin, xmax, ymin, ymax)

        dem_path = os.path.join(tmp_path, "dem.tif")
        gdal.Warp(dem_path, vrt_path,
            cutlineDSName=aoi_path,
            cropToCutline=True,
            dstSRS=utm_crs,
            xRes=30, yRes=30,
            targetAlignedPixels=True,
            dstNodata=-9999
        )

        if add_intermediate_layers:
            self.adicionar_layer(dem_path, "1. DEM")

        self.dlg.label_status.setText("Recortando DEM...")
        self.dlg.progressBar.setValue(13)
        QCoreApplication.processEvents()

        # Cobertura e uso do solo
        uso_path = os.path.join(tmp_path, "uso.tif")
        gdal.Warp(uso_path,
            "/vsicurl/https://storage.googleapis.com/mapbiomas-public/initiatives/brasil/collection_10/lulc/coverage/brazil_coverage_2024.tif",
            outputBounds=(xmin, ymin, xmax, ymax),
            outputBoundsSRS='EPSG:4326',
            cutlineDSName=aoi_path,
            cropToCutline=True,
            dstSRS=utm_crs,
            xRes=30, yRes=30,
            targetAlignedPixels=True,
            dstNodata=-9999
        )

        self.dlg.label_status.setText("Recortando Cobertura e Uso do Solo...")
        self.dlg.progressBar.setValue(25)
        QCoreApplication.processEvents()

        if add_intermediate_layers:
            self.adicionar_layer(uso_path, "2. Cobertura e Uso do Solo")

        # HAND (altura acima da drenagem mais próxima)
        hand_tiles = self.get_hand_tiles(xmin, ymin, xmax, ymax)
        hand_vrt_path = os.path.join(tmp_path, "hand_mosaic.vrt")
        gdal.BuildVRT(hand_vrt_path, hand_tiles)

        hand_path = os.path.join(tmp_path, "hand.tif")
        gdal.Warp(hand_path, hand_vrt_path,
            cutlineDSName=aoi_path,
            cropToCutline=True,
            dstSRS=utm_crs,
            xRes=30, yRes=30,
            targetAlignedPixels=True,
            dstNodata=-9999
        )

        if add_intermediate_layers:
            self.adicionar_layer(hand_path, "3. HAND")

        self.dlg.label_status.setText("Recortando HAND...")
        self.dlg.progressBar.setValue(38)
        QCoreApplication.processEvents()

        # Declividade
        decliv_path = os.path.join(tmp_path, "declividade.tif")
        processing.run("gdal:slope", {
            'INPUT': dem_path,
            'BAND': 1,
            'AS_PERCENT': True,
            'COMPUTE_EDGES': False,
            'ZEVENBERGEN': False,
            'SCALE': 1,
            'OUTPUT': decliv_path
        })

        if add_intermediate_layers:
            self.adicionar_layer(decliv_path, "4. Declividade")

        self.dlg.label_status.setText("Calculando declividade...")
        self.dlg.progressBar.setValue(50)
        QCoreApplication.processEvents()

        decliv_rec_path = os.path.join(tmp_path, "decliv_rec.tif")
        processing.run("native:reclassifybytable", {
            'INPUT_RASTER': decliv_path,
            'RASTER_BAND': 1,
            'TABLE': [-9999,2,5, 2,6,4, 6,20,3, 20,50,2, 50,99999,1],
            'NO_DATA': -9999,
            'RANGE_BOUNDARIES': 0,
            'OUTPUT': decliv_rec_path
        })

        if add_intermediate_layers:
            self.adicionar_layer(decliv_rec_path, "5. Declividade Reclassificada")

        self.dlg.label_status.setText("Reclassificando declividade...")
        self.dlg.progressBar.setValue(63)
        QCoreApplication.processEvents()

        # HAND reclassificado: menor altura acima da drenagem = maior suscetibilidade
        hand_rec_path = os.path.join(tmp_path, "hand_rec.tif")
        processing.run("native:reclassifybytable", {
            'INPUT_RASTER': hand_path,
            'RASTER_BAND': 1,
            'TABLE': [-1,1,5, 1,5,4, 5,10,3, 10,25,2, 25,9999,1],
            'NO_DATA': -9999,
            'RANGE_BOUNDARIES': 0,
            'OUTPUT': hand_rec_path
        })

        if add_intermediate_layers:
            self.adicionar_layer(hand_rec_path, "6. HAND Reclassificado")

        self.dlg.label_status.setText("Reclassificando HAND...")
        self.dlg.progressBar.setValue(75)
        QCoreApplication.processEvents()

        # Reclassifica uso do solo
        uso_rec_path = os.path.join(tmp_path, "uso_rec.tif")
        processing.run("gdal:rastercalculator", {
            'INPUT_A': uso_path, 'BAND_A': 1,
            'FORMULA': (
                '(logical_or(logical_or(A==33, A==31), A==11))*5 + '
                '(logical_or(logical_or(A==24, A==25), logical_or(A==23, A==30)))*4 + '
                '(logical_or(logical_or(A==39, A==20), logical_or(A==41, A==9)))*3 + '
                '(A==15)*2 + '
                '(logical_or(logical_or(logical_or(A==3, A==4), logical_or(A==5, A==6)), A==12))*1'
            ),
            'NO_DATA': -9999,
            'OUTPUT': uso_rec_path
        })

        if add_intermediate_layers:
            self.adicionar_layer(uso_rec_path, "7. Cobertura e Uso do Solo Reclassificado")

        self.dlg.label_status.setText("Reclassificando Cobertura e Uso do Solo...")
        self.dlg.progressBar.setValue(88)
        QCoreApplication.processEvents()

        # Combinação final
        processing.run("gdal:rastercalculator", {
            'INPUT_A': decliv_rec_path, 'BAND_A': 1,
            'INPUT_B': hand_rec_path,    'BAND_B': 1,
            'INPUT_C': uso_rec_path,     'BAND_C': 1,
            'FORMULA': f'({p_decliv}*A) + ({p_hand}*B) + ({p_solo}*C)',
            'NO_DATA': -9999,
            'OUTPUT': output_path
        })

        # a camada final é sempre adicionada, independente do checkbox
        self.adicionar_layer(output_path, "Suscetibilidade à Inundação")

        self.dlg.label_status.setText("Calculando Suscetibilidade a Inundação...")
        self.dlg.progressBar.setValue(100)
        QCoreApplication.processEvents()

        # estilo
        layer = QgsProject.instance().mapLayersByName("Suscetibilidade à Inundação")[-1]
        provider = layer.dataProvider()

        shader = QgsRasterShader()
        color_ramp = QgsColorRampShader()
        color_ramp.setColorRampType(QgsColorRampShader.Discrete)
        color_ramp.setColorRampItemList([
            QgsColorRampShader.ColorRampItem(2.2, QColor(0, 100, 0), "Muito Baixa"),
            QgsColorRampShader.ColorRampItem(3.0, QColor(150, 200, 0), "Baixa"),
            QgsColorRampShader.ColorRampItem(3.8, QColor(255, 255, 0), "Média"),
            QgsColorRampShader.ColorRampItem(4.6, QColor(255, 150, 0), "Alta"),
            QgsColorRampShader.ColorRampItem(5.0, QColor(255, 0, 0), "Muito Alta"),
        ])
        shader.setRasterShaderFunction(color_ramp)
 
        renderer = QgsSingleBandPseudoColorRenderer(provider, 1, shader)
        layer.setRenderer(renderer)
        layer.triggerRepaint()
 
        self.dlg.accept()